/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MakingChaiRouteImport } from './routes/making.chai'
import { Route as ProductsLaxyRouteImport } from './routes/Products.laxy'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MakingChaiRoute = MakingChaiRouteImport.update({
  id: '/making/chai',
  path: '/making/chai',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsLaxyRoute = ProductsLaxyRouteImport.update({
  id: '/Products/laxy',
  path: '/Products/laxy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/Products/laxy': typeof ProductsLaxyRoute
  '/making/chai': typeof MakingChaiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/Products/laxy': typeof ProductsLaxyRoute
  '/making/chai': typeof MakingChaiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/Products/laxy': typeof ProductsLaxyRoute
  '/making/chai': typeof MakingChaiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/Products/laxy' | '/making/chai'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/Products/laxy' | '/making/chai'
  id: '__root__' | '/' | '/about' | '/Products/laxy' | '/making/chai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ProductsLaxyRoute: typeof ProductsLaxyRoute
  MakingChaiRoute: typeof MakingChaiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/making/chai': {
      id: '/making/chai'
      path: '/making/chai'
      fullPath: '/making/chai'
      preLoaderRoute: typeof MakingChaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Products/laxy': {
      id: '/Products/laxy'
      path: '/Products/laxy'
      fullPath: '/Products/laxy'
      preLoaderRoute: typeof ProductsLaxyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ProductsLaxyRoute: ProductsLaxyRoute,
  MakingChaiRoute: MakingChaiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
